import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ReactNode } from "react";

const inter = Inter({ subsets: ["latin"] });

interface Props {
  children?: ReactNode;
  className?: string;
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, className }: Props) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div
          className={`bg-slate-200 mx-auto antialiased${
            className ? " " + className : ""
          }`}
        >
          {children}
        </div>
      </body>
    </html>
  );
}
