on:
  push:
    branches:
      - master

name: Publish to NPM

jobs:
  publish:
    name: Publish to NPM & GitHub Package Registry
    runs-on: ubuntu-latest
    if: contains(github.ref, 'master')

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: master

      - name: Check version changes
        uses: EndBug/version-check@v2
        id: check

      - name: Version update detected
        if: steps.check.outputs.changed == 'true'
        run: 'echo "Version change found! New version: ${{ steps.check.outputs.version }} (${{ steps.check.outputs.type }})"'

      - name: Set up Node.js for NPM
        if: steps.check.outputs.changed == 'true'
        uses: actions/setup-node@v4
        with:
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        if: steps.check.outputs.changed == 'true'
        run: npm install --only=prod

      - name: Publish package to NPM
        if: steps.check.outputs.changed == 'true'
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
