on:
  push:
    branches:
      - master

name: Publish to NPM

jobs:
  publish:
    name: Publish to NPM
    runs-on: ubuntu-latest
    if: contains(github.ref, 'master')

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: master

      - name: Set up Node.js for NPM
        uses: actions/setup-node@v4
        with:
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: npm install --only=prod

      - name: Publish package to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
